name: Auto-fill PR with Commit Messages

on:
  pull_request:
    types: [opened]

jobs:
  update-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get the pull request number
      id: pr
      run: echo "::set-output name=pr_number::${{ github.event.pull_request.number }}"

    - name: Get commit messages
      id: commits
      run: |
        commit_messages=$(git log --pretty=format:"%h - %s" ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
        echo "::set-output name=messages::${commit_messages}"

    - name: Update pull request description
      run: |
        gh pr edit ${{ steps.pr.outputs.pr_number }} --body "${{ github.event.pull_request.body }}\n\n### Commits in this PR:\n${{ steps.commits.outputs.messages }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
